# Site settings
title: Pete Russell
email: pete.russell01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pete Russell: software development, flying, climbing, running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peterussell.me" # the base hostname & protocol for your site
twitter_username: nz_pete
github_username:  peterussell

# Build settings
markdown: kramdown

paginate: 4

author: Pete Russell

gems: [jekyll-paginate]
